package com.example.kuliza306.zolostayssample.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "UserInfoData".
 */
public class UserInfoData {

    private String phoneNumber;
    private String emailId;
    private String name;
    private String password;

    // KEEP FIELDS - put your custom fields here

    // KEEP FIELDS END

    public UserInfoData() {
    }

    public UserInfoData(String phoneNumber, String emailId, String name, String password) {
        this.phoneNumber = phoneNumber;
        this.emailId = emailId;
        this.name = name;
        this.password = password;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
