package com.example.kuliza306.zolostayssample.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.kuliza306.zolostayssample.database.UserInfoData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UserInfoData".
*/
public class UserInfoDataDao extends AbstractDao<UserInfoData, Void> {

    public static final String TABLENAME = "UserInfoData";

    /**
     * Properties of entity UserInfoData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PhoneNumber = new Property(0, String.class, "phoneNumber", false, "PHONE_NUMBER");
        public final static Property EmailId = new Property(1, String.class, "emailId", false, "EMAIL_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Password = new Property(3, String.class, "password", false, "PASSWORD");
    };


    public UserInfoDataDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UserInfoData\" (" + //
                "\"PHONE_NUMBER\" TEXT," + // 0: phoneNumber
                "\"EMAIL_ID\" TEXT," + // 1: emailId
                "\"NAME\" TEXT," + // 2: name
                "\"PASSWORD\" TEXT);"); // 3: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UserInfoData\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserInfoData entity) {
        stmt.clearBindings();
 
        String phoneNumber = entity.getPhoneNumber();
        if (phoneNumber != null) {
            stmt.bindString(1, phoneNumber);
        }
 
        String emailId = entity.getEmailId();
        if (emailId != null) {
            stmt.bindString(2, emailId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(4, password);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public UserInfoData readEntity(Cursor cursor, int offset) {
        UserInfoData entity = new UserInfoData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // phoneNumber
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // emailId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // password
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserInfoData entity, int offset) {
        entity.setPhoneNumber(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEmailId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPassword(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(UserInfoData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(UserInfoData entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
